### ISSUE TITLE
GDAL_HDF4_support

### ISSUE THREAD

**Issue by lpalao** [lucadelu/pyModis#29] opened 2015-03-25 01:53 UTC
Hi PyModis Users,

Good day!

I would want to use pyMODIS to download MODIS data but I am faced with some challenges. Could I ask for some guidance?

Here is the error message that I am receiving when running the code:

runfile('E:/Python_scripts/pyModis_download.py', wdir='E:/Python_scripts')
Traceback (most recent call last):
  File "<ipython-input-32-e2211f1b79c5>", line 1, in <module>
    runfile('E:/Python_scripts/pyModis_download.py', wdir='E:/Python_scripts')
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)
  File "E:/Python_scripts/pyModis_download.py", line 19, in <module>
    tiles='h26v06', path='MOLT', product='MOD13Q1.005', today=2015-01-01, enddate=2015-03-24)
  File "C:\Anaconda\lib\site-packages\pymodis\downmodis.py", line 272, in __init__
    raise IOError("GDAL installation has no support for HDF4, please"
IOError: GDAL installation has no support for HDF4, please update GDAL

In the end it says: GDAL installation has no support for HDF4, please update GDAL.

Then I tried to update my Python GDAL version using 
>>> pip install GDAL --upgrade

But it seems that my GDAL version is up-to-date. With regards to my GDAL core installer from GISinternals, I just downloaded and installed it this February 2015.

Could you help me trouble shoot this issue?

This is the code that I am trying to test.

import os
import pymodis
from pymodis import downmodis
ws = 'E:/Test'
#tile = 'h26v06'
#prod = 'MOD11C2.005'
#day = '2014-01-01'
#end = '2014-01-01'
pymodis.downmodis.downModis(ws, url='http://e4ftl01.cr.usgs.gov',\
tiles='h26v06', path='MOLT', product='MOD13Q1.005', today=2015-01-01, enddate=2015-03-24)

Thanks and all the best.
-Leo

**Comment by lucadelu** [comment] 2015-03-26 11:18
Hi, the problem is that GDAL on Windows is compiled without HDF4 support; GDAL it is used by this class only to check if the file is downloaded correctly I could add new parameter to ask if perform this check or not.

I could fix this problem in the next days, but I'm really busy now

**Comment by lpalao** [comment] 2015-03-30 00:26
Thanks Luca for fixing the HDF4 issue in windows.
-Leo

**Comment by lpalao** [comment] 2015-04-17 04:43
Hi Luca, I just would like to follow up if pyMODIS already works with GDAL on windows without requiring to have a HDF4 package in GDAL.
Thanks,-Leo

**Comment by lucadelu** [comment] 2015-04-27 15:07
I just release [new version](https://github.com/lucadelu/pyModis/releases/tag/1.0.1) of pyModis and this bug should be fixed, please test it. If it works please close the ticket

**Comment by lpalao** [comment] 2015-05-08 05:58
Hi Luca, I just updated my pymodis to 1.0.1

I still the error GDAL installation has no support for HDF4

This is the command that I am running.

C:\Anaconda\Scripts> python modis_download.py -r -t h18v03,h18v04 -f
2008-01-01 -e 2008-01-31 E:/Test/

Thanks,
-Leo

**Comment by lucadelu** [comment] 2015-05-11 07:59
Could you please test branch 1.0, it should work now.

**Comment by lpalao** [comment] 2015-05-19 03:13
Hi Luca, I downloaded the new version of pyMODIS (hopefully this is the one
you are referring to -- *test branch 1.0*) version 1.0.1.zip

I uninstall first the pyModis that I currently have, then reinstall it
using the pyMODIS that I downloaded from the GitHub site (
https://github.com/lucadelu/pyModis/releases/tag/1.0.1). I installed it
using python setup.py install

I tried to run the command modis_download.py -r -t h18v03,h18v04 -f
2008-01-01 -e 2008-01-31 lst_terra/

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\path>cd C:\Anaconda\Scripts

C:\Anaconda\Scripts>python modis_download.py -r -t h18v03,h18v04 -f
2008-01-01 -e 2008-01-31 E:/Test/

Traceback (most recent call last):
  File "modis_download.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyModis==1.0.1',
'modis_download.py')
  File
"C:\Anaconda\lib\site-packages\setuptools-14.0-py2.7.egg\pkg_resources\__init__.py",
line 698
, in run_script

  File
"C:\Anaconda\lib\site-packages\setuptools-14.0-py2.7.egg\pkg_resources\__init__.py",
line 162
3, in run_script

  File
"C:\Anaconda\lib\site-packages\pymodis-1.0.1-py2.7.egg\EGG-INFO\scripts\modis_download.py",
l
ine 136, in <module>

  File
"C:\Anaconda\lib\site-packages\pymodis-1.0.1-py2.7.egg\EGG-INFO\scripts\modis_download.py",
l
ine 125, in main

  File "build\bdist.win32\egg\pymodis\downmodis.py", line 278, in __init__
IOError: GDAL installation has no support for HDF4,  please update GDAL

C:\Anaconda\Scripts>

**Comment by lucadelu** [comment] 2015-05-20 10:56
The right version to test is https://github.com/lucadelu/pyModis/archive/1.0.zip, please with this.

**Comment by tr-gis** [comment] 2015-05-22 09:16
hello,

I have been having the same issue too. I installed it by using the setup.py file that was in the link lucadelu gave but still when trying to import pymodis in python I get the following message 

"GDAL installation has no support for HDF4, please update GDAL"

~cheers

**Comment by lpalao** [comment] 2015-05-22 23:26
Hi Luca, just installed it and it is working now. Will let you if there are
issues. By the way, will it be nice to have a progress bar when downloading?

Thank you very much.
-Leo

**Comment by tr-gis** [comment] 2015-05-25 10:10
Well I don't know how but the issue got resolved. Thanks Luca. Great Job :)

**Comment by lucadelu** [comment] 2015-05-25 10:18
Maybe because the pip version was used instead the one installed from source code.
Ipalao please open a new ticket for the progress bar.

Closing this ticket as resolved

**Closed by lucadelu** 2015-05-25 10:18 UTC
Labels: bug

**Comment by Gundisalv** [comment] 2015-07-08 16:55
Hello @lucadelu  I'm triying to use modis_download.py in Windows, I have installed the last pymodys from pip but it still has the problem with the HDF4 not supported on gdal, I've tried several gdal intallations but it simply does not work. Any thougths?

**Comment by bidhya** [comment] 2015-07-10 21:21
Getting the same error on pyModis on windows 7 with Enthought Canopy
Running the example script
modisDown = downmodis.downModis(destinationFolder=dest, tiles=tiles, today=day, delta=delta)
results in following error

IOError: GDAL installation has no support for HDF4,  please update GDAL

**Comment by lucadelu** [comment] 2015-07-27 07:54
@Gundisalv @bidhya,

please can you update pyModis to version 1.0.2 and try again?

**Comment by pynapkin** [comment] 2015-08-09 19:30
@lucadelu I'm having the exact same problem, currently have pyModis 1.0.2 installed and it gives me the "GDAL installation has no support for HDF4, please update GDAL"  when I try to download Modis data, even though I have the most up to date version of GDAL installed.

**Comment by Gundisalv** [comment] 2015-08-10 20:36
Already updated it, same issue

**Comment by lizsz** [comment] 2016-03-04 01:14
Just installed 1.0.2 from github. When importing pyModis get the same 

```
>import pymodis
GDAL installation has no support for HDF4, please update GDAL

>pymodis.__version__
'1.0.2'
```

**Comment by lucadelu** [comment] 2016-03-04 07:26
@lizsz is your OS windows? can you try `gdaling --formats` and if **HDF4** is in the output list?

If it is not there it is not a pyModis package but an issue with GDAL package of your OS

**Comment by sterben31** [comment] 2016-09-20 03:18
alguien sabe porque cuando importo pymodis no me reconoce gdal, sabiendo que ya esta instalado??

>>> import pymodis
WARNING: Python GDAL library not found, please install it to check data downloaded with pyModis

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pymodis
  File "build\bdist.win32\egg\pymodis\__init__.py", line 7, in <module>
  File "build\bdist.win32\egg\pymodis\qualitymodis.py", line 49, in <module>
ImportError: Python GDAL library not found, please install python-gdal
>>>

**Comment by lucadelu** [comment] 2016-10-24 15:18
@sterben31 could you try the last master? I added some more check and now download should work also without python-gdal
