### ISSUE TITLE
Authentication problem with default server

### ISSUE THREAD

**Issue by zschira** [lucadelu/pyModis#59] opened 2016-07-28 19:06 UTC
The default http server, 'http://e4ftl01.cr.usgs.gov', has been updated to require a Nasa earthdata account  when downloading files. I do not believe there are any methods in the default package for http authentication.

**Comment by lucadelu** [comment] 2016-07-28 21:34
Yes, I know. I hope to fix it in the next weeks

**Comment by lucadelu** [comment] 2016-07-28 21:37
the error should be

`  File "/usr/local/bin/modis_download.py", line 125, in <module>
    main()
  File "/usr/local/bin/modis_download.py", line 119, in main
    modisOgg.downloadsAllDay(clean=options.empty, allDays=options.alldays)
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 607, in downloadsAllDay
    self._downloadsAllDayHTTP(days)
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 621, in _downloadsAllDayHTTP
    self.dayDownload(day, listFilesDown)
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 588, in dayDownload
    self.downloadFile(i, file_hdf, day)
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 486, in downloadFile
    self._downloadFileHTTP(filDown, filHdf, day)
  File "/usr/local/lib/python2.7/dist-packages/pymodis/downmodis.py", line 501, in _downloadFileHTTP
    http = urllib2.urlopen(urljoin(self.url, self.path, day, filDown))
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
`

**Comment by sobralm** [comment] 2016-08-09 00:21
Hi, I'd like to know if the issue can be solved.  I'm still having 401 error when earth data authorizes the download.

Best regards

"2016-08-08 23:34:25,206 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-08-08 23:34:25,279 - DEBUG - "GET /MOLT/MOD13Q1.005/2016.06.25/MOD13Q1.A2016177.h13v09.005.2016200071435.hdf.xml HTTP/1.1" 302 525
2016-08-08 23:34:25,280 - INFO - Starting new HTTPS connection (1): urs.earthdata.nasa.gov
2016-08-08 23:34:25,403 - DEBUG - "GET /oauth/authorize?scope=uid&app_type=401&client_id=ijpRZvb9qeKCK5ctsn75Tg&response_type=code&redirect_uri=http%3A%2F%2Fe4ftl01.cr.usgs.gov%2Foauth&state=aHR0cDovL2U0ZnRsMDEuY3IudXNncy5nb3YvTU9MVC9NT0QxM1ExLjAwNS8yMDE2LjA2LjI1L01PRDEzUTEuQTIwMTYxNzcuaDEzdjA5LjAwNS4yMDE2MjAwMDcxNDM1LmhkZi54bWw HTTP/1.1" 401 None
2016-08-08 23:34:25,404 - ERROR - Cannot download MOD13Q1.A2016177.h13v09.005.2016200071435.hdf.xml. Retrying.."

**Comment by lucadelu** [comment] 2016-08-09 13:49
@sobralm I really hope yes, I'm working on it without a solution yet.

**Comment by Gonzant** [comment] 2016-08-10 02:25
Hello, i was working on the same on python 3.
This is how I resolve it.
Change user and password and the url is for example.
I hope it help you.

import urllib.request
import urllib.error
import http.cookiejar
from base64 import b64encode

try:
	userAndPass = b64encode(b"user:password").decode("ascii")		
	header = { 'Authorization' : 'Basic %s' %  userAndPass }			
	url = 'http://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.005/2000.03.05/MOD13Q1.A2000065.h32v12.005.2008238033320.hdf'

	class MyHTTPRedirectHandler(urllib.request.HTTPRedirectHandler):
		def http_error_302(self, req, fp, code, msg, headers):
			return urllib.request.HTTPRedirectHandler.http_error_302(self, req, fp, code, msg, headers)		

	cookieprocessor = urllib.request.HTTPCookieProcessor()
	
	opener = urllib.request.build_opener(MyHTTPRedirectHandler, cookieprocessor)
	urllib.request.install_opener(opener)

	req = urllib.request.Request(url,headers = header)	
	req.add_header('Authorization' , 'Basic %s' %  userAndPass)
	x = urllib.request.urlopen(req)			
	
	print(x.read())	
	
except urllib.error.URLError as e:	
	print(e)

**Comment by lucadelu** [comment] 2016-08-10 13:51
@Gonzant thanks a lot for the code. It work and I'm going to implement it in the 2.0 branch that it work with python3.

Is ```req.add_header('Authorization' , 'Basic %s' %  userAndPass)``` required? I tried without and it seems to work...

**Comment by lucadelu** [comment] 2016-08-12 14:30
I implemented the solution proposed by @Gonzant into branch 2.0 with this commit e8d36a3
Please try it, next week I'll release a new version of pyModis

**Comment by lucadelu** [comment] 2016-08-22 21:54
I backported all the code from branch 2.0 to master, please let me know if it works.

I would like to release pyModis version 2.0 by this week

**Comment by Kavindagunasekara** [comment] 2016-08-24 13:45
Hi Luca, waiting for the ver 2.0 to get solved the Authentication issue. Thanks a lot!!!

**Comment by lucadelu** [comment] 2016-08-28 07:31
Yesterday pyModis 2.0.1 was released, please test it and report bugs (if needed)

Please let me know if it working for you so I could close the ticket

**Comment by Kavindagunasekara** [comment] 2016-08-29 02:12
Hi, I already updated to new version. please help me on below error, I may doing a mistake

2016-08-29 11:08:09,652 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-08-29 11:08:09,831 - DEBUG - Setting read timeout to 30
2016-08-29 11:08:10,005 - DEBUG - "GET /MOLT/MOD13Q1.005/2010.12.19 HTTP/1.1" 301 263
2016-08-29 11:08:10,005 - DEBUG - Setting read timeout to 30
2016-08-29 11:08:12,202 - DEBUG - "GET /MOLT/MOD13Q1.005/2010.12.19/ HTTP/1.1" 200 None
2016-08-29 11:08:13,530 - ERROR - Cannot download MOD13Q1.A2010353.h11v03.005.2011006235441.hdf. Retrying...
2016-08-29 11:08:18,890 - ERROR - Cannot download MOD13Q1.A2010353.h11v03.005.2011006235441.hdf. Retrying...

**Comment by lucadelu** [comment] 2016-08-29 08:18
@Kavindagunasekara did you register [here](https://urs.earthdata.nasa.gov//users/new)?

if yes could you send me the line command launched to download the data? (please send the command line without the password)

**Comment by Kavindagunasekara** [comment] 2016-08-29 15:18
yes, I have registered. also created new account to check. I used your given sample code as well but get same error. my original code is in bash file where I use modis_download.py, modis_mosaic.py and modis_convert.py then use gdal library to mask data to study area. I will change the login password later.

modis_download.py -U okith -P Japan2014 -r -p MOD13Q1.005 -f 2010-12-31 -O tmp/

**Comment by Kavindagunasekara** [comment] 2016-09-03 08:41
Thanks Luca. Yes, I can download data manually, even given link my you also successful. When script is running I can see corresponding data file is appearing in the folder for a second then disappear.

**Comment by lucadelu** [comment] 2016-09-04 23:17
@Kavindagunasekara  I really don't know, I'm not able to replicate your problem. Which is your OS (it seems linux)?

**Comment by Kavindagunasekara** [comment] 2016-09-05 11:30
Hi Lucas, it's linux and python 2.7. thanks for your time

**Comment by jcabdala** [comment] 2016-09-05 22:02
Equal to me:
modis_download.py -U user -P pass -r -s MOLA -p MYD13Q1.005 -t h12v12 -f 2016-07-03 -O /temp

log:
2016-09-05 18:45:48,811 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-09-05 18:45:49,271 - DEBUG - "GET /MOLA/MYD13Q1.005 HTTP/1.1" 301 252
2016-09-05 18:45:49,495 - DEBUG - "GET /MOLA/MYD13Q1.005/ HTTP/1.1" 200 None
2016-09-05 18:45:49,960 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-09-05 18:45:50,437 - DEBUG - "GET /MOLA/MYD13Q1.005/2016.07.03 HTTP/1.1" 301 263
2016-09-05 18:45:50,999 - DEBUG - "GET /MOLA/MYD13Q1.005/2016.07.03/ HTTP/1.1" 200 None
2016-09-05 18:45:54,145 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf.xml. Retrying...
2016-09-05 18:46:00,655 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf.xml. Retrying...
2016-09-05 18:46:07,124 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf.xml. Retrying...
2016-09-05 18:46:13,618 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf.xml. Retrying...

I check user and pass with navigator in http://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.005/ and works

**Comment by chingchai** [comment] 2016-09-06 01:55
Hi Luca, I used pyModis-2.0.2 and I tested download modis in path Downloading data from http://www.pymodis.org/examples/full_example_gdal.html
modis_download.py -I -f 2012-12-05 -O -t h28v05,h29v05,h28v04 $HOME/tmp

log:
2016-09-06 08:50:40,445 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-09-06 08:50:41,014 - DEBUG - Setting read timeout to 30
2016-09-06 08:50:41,394 - DEBUG - "GET /MOLT/MOD11A1.005 HTTP/1.1" 301 252
2016-09-06 08:50:41,398 - DEBUG - Setting read timeout to 30
2016-09-06 08:50:42,029 - DEBUG - "GET /MOLT/MOD11A1.005/ HTTP/1.1" 200 None
2016-09-06 08:50:47,053 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-09-06 08:50:48,050 - DEBUG - Setting read timeout to 30
2016-09-06 08:50:48,460 - DEBUG - "GET /MOLT/MOD11A1.005/2012.12.05 HTTP/1.1" 301 263
2016-09-06 08:50:48,463 - DEBUG - Setting read timeout to 30
2016-09-06 08:50:50,305 - DEBUG - "GET /MOLT/MOD11A1.005/2012.12.05/ HTTP/1.1" 200 None
2016-09-06 08:50:54,925 - ERROR - Cannot download MOD11A1.A2012340.h29v05.005.2012342062359.hdf. Retrying...
2016-09-06 08:51:00,658 - ERROR - Cannot download MOD11A1.A2012340.h29v05.005.2012342062359.hdf. Retrying...
2016-09-06 08:51:06,538 - ERROR - Cannot download MOD11A1.A2012340.h29v05.005.2012342062359.hdf. Retrying...
2016-09-06 08:51:12,220 - ERROR - Cannot download MOD11A1.A2012340.h29v05.005.2012342062359.hdf. Retrying...
2016-09-06 08:51:18,180 - ERROR - Cannot download MOD11A1.A2012340.h29v05.005.2012342062359.hdf. Retrying...
2016-09-06 08:51:24,506 - ERROR - Cannot download MOD11A1.A2012340.h29v05.005.2012342062359.hdf. Retrying...

**Comment by diegoschell** [comment] 2016-09-06 12:30
Hi Luca, I have the same problem. I upgrade to pyModis-2.0.2 and I tested modis download running on Linux and python 2.7:

modis_download.py -I -r -t h13v11 -p MOD13Q1.005 -e 2000-01-01 -f 2010-04-23 /tmp

log:

2016-09-06 09:17:26,666 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-09-06 09:17:27,582 - DEBUG - "GET /MOLT/MOD13Q1.005 HTTP/1.1" 301 252
2016-09-06 09:17:27,856 - DEBUG - "GET /MOLT/MOD13Q1.005/ HTTP/1.1" 200 None
2016-09-06 09:17:28,651 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2016-09-06 09:17:29,201 - DEBUG - "GET /MOLT/MOD13Q1.005/2010.04.23 HTTP/1.1" 301 263
2016-09-06 09:17:30,882 - DEBUG - "GET /MOLT/MOD13Q1.005/2010.04.23/ HTTP/1.1" 200 None
2016-09-06 09:17:34,208 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:17:40,984 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:17:47,704 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:17:54,780 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:01,495 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:08,292 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:15,058 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:21,963 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:28,687 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:35,411 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:42,256 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:49,412 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:18:56,141 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:02,869 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:09,766 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:16,500 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:23,247 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:29,979 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:36,832 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:43,559 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:50,402 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:19:57,131 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...
2016-09-06 09:20:03,957 - ERROR - Cannot download MOD13Q1.A2010113.h13v11.005.2010134052851.hdf. Retrying...

Thanks for your time.

**Comment by lucadelu** [comment] 2016-09-06 22:04
Hi all, I'm really sorry but I'm not able to reproduce your error, several user on different linux platform. I updated the documentation related to user and password, [please read it](http://www.pymodis.org/info.html#user-and-password).

Otherwise you should try to debug it using [pdb](https://docs.python.org/3.2/library/pdb.html) or [ipdb](https://pypi.python.org/pypi/ipdb). You should modify the file [downmodis.py adding after line 639](https://github.com/lucadelu/pyModis/blob/master/pymodis/downmodis.py#L639) 

`import pdb; pdb.set_trace()`

and later when a python console will appear you have to digit 

```
print(self.header)
print(url)
```

Please report the output of this two commands, thanks.

Is someone using Python 3?

**Comment by jcabdala** [comment] 2016-09-07 13:06
I use ipdb with 
**_modis_download.py -U user -P pass -r -s MOLA -p MYD13Q1.005 -t h12v12 -f 2016-07-03 -O /temp_**

and return that

> print(self.header)
> AttributeError: "downModis instance has no attribute 'header'"
> print(url) 
>http//e4ftl01.cr.usgs.gov/MOLA/MYD13Q1.005/2016.07.03/MYD13Q1.A2016185.h12v12.005.2016202025535.hdf.xml


I check with 2.7 in virtaulenvs beacuse in python3 I have ImportError: Python GDAL library not found, please install python-gdal

**Comment by jcabdala** [comment] 2016-09-07 13:16
I repair the  gdal error wit python3 
pip install GDAL==2.1.0 --global-option=build_ext --global-option="-I/usr/include/gdal"

And I have the same problem:

> 2016-09-07 10:14:57,317 - WARNING - WARNING: Python GDAL library not found
> 2016-09-07 10:14:57,327 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
> 2016-09-07 10:14:58,301 - DEBUG - "GET /MOLA/MYD13Q1.005 HTTP/1.1" 301 252
> 2016-09-07 10:14:58,539 - DEBUG - "GET /MOLA/MYD13Q1.005/ HTTP/1.1" 200 None
> 2016-09-07 10:14:58,991 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
> 2016-09-07 10:14:59,470 - DEBUG - "GET /MOLA/MYD13Q1.005/2016.07.03 HTTP/1.1" 301 263
> 2016-09-07 10:15:00,447 - DEBUG - "GET /MOLA/MYD13Q1.005/2016.07.03/ HTTP/1.1" 200 None
> 2016-09-07 10:15:02,999 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf. Retrying...
> 2016-09-07 10:15:10,386 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf. Retrying...
> 2016-09-07 10:15:17,015 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf. Retrying...
> 2016-09-07 10:15:23,486 - ERROR - Cannot download MYD13Q1.A2016185.h12v12.005.2016202025535.hdf. Retrying...

**Comment by jcabdala** [comment] 2016-09-07 14:00
Debugging I find that 
_urllib.error.HTTPError: HTTP Error 401: Unauthorized_
in 
_http = urllib.request.urlopen(req)_

I dont understand why, I was loggin in chrome and if I copy the url 
_e4ftl01.cr.usgs.gov/MOLA/MYD13Q1.005/2016.07.03/MYD13Q1.A2016185.h12v12.005.2016202025535.hdf.xml_
(whitout "http://") Download 

I check “My application” tab  and its right

**Comment by jcabdala** [comment] 2016-09-07 16:18
FIX 
I create other user and and approve the applications “LP DAAC Data Pool” and “Earthdata Search”. And Works python 2 and 3 with pymodis 2.0.2

**Comment by diegoschell** [comment] 2016-09-07 17:32
Hi Luca, 

I create a new user and works fine. Thank you very much for your work!

**Comment by lucadelu** [comment] 2016-09-08 15:35
ok, so according to the last comments I close this ticket.

For people still having problem please check you authorization credentials.

**Closed by lucadelu** 2016-09-08 15:35 UTC
Labels: bug

**Comment by kalxas** [comment] 2016-10-14 09:25
I have also had this issue.
This morning I changed my password to remove some characters like $ and now I am able to start downloading.
So far only the xml file gets here, I suppose the server is slow today...

**Comment by kalxas** [comment] 2016-10-14 09:26
I am now also testing #67

**Comment by kalxas** [comment] 2016-10-14 09:40
Still not working on a production Ubuntu Precise server.

**Comment by kalxas** [comment] 2016-10-14 11:26
In case someone else has similar issues, just use miniconda to get gdal 2.1 from conda-forge.
Problem solved for me.

**Comment by jcabdala** [comment] 2016-10-14 13:37
kalxas  to production service I create and edit a fork https://github.com/jcabdala/pyModis

Check the changes: 
https://github.com/jcabdala/pyModis/commit/7dc461ae149a1e057fd3f738b398c35d7d0a7861

**Comment by kalxas** [comment] 2016-10-14 14:06
thanks @jcabdala
