### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Kavindagunasekara** [lucadelu/pyModis#23] opened 2015-01-16 03:45 UTC
Hi all,
I tried all the installation options avalable in the page and also followed the trobleshooting methods. All the time this is the error message during the installation "warning C4530: c++ exception handler used, but unwind semantics are not enabled. Specify /EHsc" . I think it related to http://msdn.microsoft.com/en-us/library/2axwkyt4.aspx

I don`t have much idea on how to enable that. Your help is highly appreciated. Hope this is the correct place for this post if not please redirect me. Thanks!

**Comment by lucadelu** [comment] 2015-01-20 14:13
Hi, 
are you able to install GDAL and numpy? what is the Windows' version?
I tried with Windows 7 and I had problem with GDAL *error: Unable to find vcvarsall.bat*; at the end I solved installing gdal and numpy using osgeo4w and from OSGeo shell I installed pyModis using the source code.

I'll update the docs according the new solution

**Comment by Kavindagunasekara** [comment] 2015-01-20 14:47
Thanks lot for your reply Luca. 

Still I couldn't solve it. I tried whole day today. When I try on Windows 7 got the same error "Unable to find vcvarsall.bat". I tried on windows 7 and 8 both. I tried osgeo4w to install GDAL on windows 7 (Japaneses OS) but failed. As you already succeeded, I will try again in my Windows 7 (English OS) machine, will write here again tomorrow. 

BTW, I'm thinking to buy a Mac, will that be easy to work with this library?? I really want to run pyModis tools as early as possible. Thanks again for your contribution !!!

**Comment by lucadelu** [comment] 2015-01-20 15:07
Hi Kevinda,
I'm sorry that you had a lot of problems, but most of them seem not directly related to pyModis.
 
the error vcvarsall.bat is related to missing visual studio. For the problem of gdal with japaneses OS could I suggest you to check in the GDAL ticket system to see if the problem is already reported.

Could I suggest you to use Linux? it should be the simpler OS to work with FOSS softwares; you could also create a virtual machine using virtual box.

**Comment by Kavindagunasekara** [comment] 2015-01-21 10:23
Hi Luca,

Of course it's not pyModis problem!!! sorry if you felt like that from my previous message. I tried with osgeo4w in both windows 7 & 8 (English OS) but still failed. GDAL installation goes inside the osgeo directory and couldn't import the pyModis library. Sometime I am making a mistake, will try to figure out myself, if continuously fail will send you a screenshots. BTW, I am installing Ubuntu for another PC in parallel. Thanks! will write here again :)

**Comment by lucadelu** [comment] 2015-01-21 10:40
Hi Kevinda,

if you are able to install GDAL and numpy now you can install pyModis using the OSGeo4W shell.

Download the [source code](https://github.com/lucadelu/pyModis/archive/1.0.0.zip) and install it using python from OSGeo4W shell.

Yesterday I was able to do that on windows 7 machine

**Comment by Kavindagunasekara** [comment] 2015-01-21 11:02
Hi Luca,

Thanks for the quick reply. I did that too. Please check this document with screenshot if you have time. https://docs.google.com/document/d/1wKHiNW_2gDteL6-IGFIHIx_7izvZRvOYIWmzjDTsmgg/edit?usp=sharing

You can write any comment inside the doc if you want! thanks.

**Comment by Kavindagunasekara** [comment] 2015-01-26 01:38
Hi Luca,
I am working in Ubuntu now and new to the system. Please let me know how to add path of gdal, numpy and pymodis to sys.path. I`m using canoy to run the pymodis and attached herwith my screenshots. Thanks. Have nice day!
![selection_001](https://cloud.githubusercontent.com/assets/9985296/5894341/4fa4f764-a547-11e4-8d2d-57029238c29f.png)
![selection_002](https://cloud.githubusercontent.com/assets/9985296/5894342/518fbd70-a547-11e4-8bd0-d54811581af7.png)

**Comment by lucadelu** [comment] 2015-01-26 07:11
Probably python-gdal is really missing. Try to install it with "sudo apt-get install python-gdal"

**Comment by Kavindagunasekara** [comment] 2015-01-26 07:20
Thanks Luca, I already did it, pls see the below screenshot. I refer this blog page for that: http://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip
(in parallel, trying mac too. it completed python-gdal but when I am trying your iPython notebook example, it says have to install HDF4 support for gdal, I`m working in that too). BTW, learning lot !!! :):)
![selection_009](https://cloud.githubusercontent.com/assets/9985296/5896376/3d7c4ca6-a577-11e4-91e6-750e17518b46.png)

**Comment by lucadelu** [comment] 2015-01-26 07:42
The name of the gdal library in Python is osgeo.gdal, so you should try *import osgeo.gdal as gdal* 
For the MAC problem is related to missing HDF4 support for gdal, for this I think someone should compile again gdal adding HDF4 support.

**Comment by Kavindagunasekara** [comment] 2015-01-26 08:02
in your downmodis.py it has compiled that way "import osgeo.gdal as gdal" line 57. hope you have mentioned that in your last comment. I understood the MAC issue, if I solved will post here. Thanks again !!!
![selection_010](https://cloud.githubusercontent.com/assets/9985296/5896691/f7d672c0-a57c-11e4-91e3-2a0883676490.png)

**Comment by Kavindagunasekara** [comment] 2015-02-17 10:49
Hi Luca,

I have solved the installation. Reinstalled ubuntu and followed below steps. Just wanted to share
1. Reinstall Ubuntu
2. installed gdal-bin
     sudo apt-get install gdal-bin
3. install pip
   sudo apt-get install python-pip
4. used pip to install pymodis but doesn`t work (gave again error on gdal-python, run this again sudo apt-get install gdal-pip
5. compile from source, then installation OK
6. gave error: name `wx` is not defined
      without having much knowledge, uninstalled pymodis using pip then reinstalled pymodis using pip (I think this is not necessary though)
7. then still `wx` error exist, then try to import numpy, gdal; those are working properly
8. then run this sudo apt-get install python-wxgtk2.8
9. Finally it`s working

Thanks for your help!

BTW, can you help on this?
When I run this: modis_download.py -f 2014-09-01 -e 2014-09-30 -t h28v06,h27v06,h28v07 -s MOLT -p MOD09GQ.005 /tmp/2014MOD

getting this: IOError: The first day should be newer then end date but  I think it is correctly given.

**Comment by lucadelu** [comment] 2015-03-09 16:02
in the last master python-wxgtk should no more required.

The date problem is that you should inverted the dates, also this should be fixed in the last master.

**Comment by lucadelu** [comment] 2015-09-17 00:59
@Kavindagunasekara could this issue considered solved?

**Comment by lucadelu** [comment] 2016-02-03 09:38
please reopen if needed

**Closed by lucadelu** 2016-02-03 09:38 UTC
Labels: question
